name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - name: Install acorn
        run: npm i -g acorn@8.7.1
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
          stable: false
      - name: Run Unit Tests
        run: go test ./...